apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
parameters:
  fsType: ext4
  iopsPerGB: '5'
  type: io1
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
