apiVersion: v1
data:
  user.conf: |-
    max_connections = 120
    shared_buffers = 20GB
    effective_cache_size = 60GB
    maintenance_work_mem = 2GB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 500
    random_page_cost = 1.1
    effective_io_concurrency = 300
    work_mem = 34952kB
    min_wal_size = 4GB
    max_wal_size = 8GB
    max_worker_processes = 30
    max_parallel_workers_per_gather = 15
    max_parallel_workers = 30
kind: ConfigMap
metadata:
  name: timescale-pg-custom-config
  namespace: default
