---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adapter
  name: adapter
  namespace: default
spec:
  ports:
  - name: http
    port: 9201
    protocol: TCP
    targetPort: http
  selector:
    app: adapter
  type: LoadBalancer
  